// AUTO-GENERATED by scripts/gen-vhe-keys.ts — DO NOT EDIT
// 重新生成会让所有 sealed key 失效，需要同步更新 desktop-newapi-sealed.generated.ts。
import type { VheConfig } from "./desktop-vhe-vm";

export const VHE_CONFIG: VheConfig = {
  opcodes: {
    "LOAD_W": 248,
    "LOAD_IV": 120,
    "LOAD_C": 72,
    "LOAD_PRIV_KEY": 108,
    "LOAD_PUB_KEY": 166,
    "RSA_OAEP_UNSEAL": 187,
    "RSA_OAEP_SEAL": 152,
    "AES_GCM_OPEN": 20,
    "AES_GCM_SEAL": 62,
    "GEN_AES_KEY": 21,
    "GEN_IV": 22,
    "EMIT_W": 236,
    "EMIT_IV": 28,
    "EMIT_C": 100,
    "WIPE": 150,
    "NOP": 43,
    "RETURN": 222
  },
  mask: "duG_yGcb4UsXYwm6jk1XP9XsLnqEmWnyIVl8FrsoC6A",
  version: 1777993779,
};

/** RSA-4096 SPKI 公钥（base64url，VHE 客户端 seal 用） */
export const VHE_PUBLIC_KEY_B64 = "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2HlJwcUyQyE0olU5zadgezr8EB0SlzZWoZt7Y6ybk4xaTZfnNkckcnZmIYym6qEaYN0N8FvIRNsduB-f0I3EtoEdfBQ8wYxBZljZ-rvuGlwQcq97-SNsqexxF1K3AqI6QszYkxbUg35jwgoJX9niMqaL2RPL1-fO3CGDPpUUW5YWFZe3MjfUonETOsiHdaAi0YyzrXO_nRBfwLZCqao8A_5a19CbYrS-tdxAimW_DCKp1pQV_1kj7oNj64tYBAMyxDtgUyKcL6LWsH6ksT_kivrugJb7zgKKGKX3dl00rWIL4-UT---sNggffkBUPujmcMz5nXgmlGC2_VFD3FJJ1MuuBmGUfeBFxf5g0qMfrXjblhlfvR9eEhLmMNOMq6d_MPHbgc4iBEOa6JTkzPq_P7uAPwwq4dtoVn2juJobOfjfr1obEHvt8fQNjSyMe5ZGCep5Nn73RS1r5xnsD_fIOuGr7XH_qkrohgwpTjWQIvRhZkEtdvvAFCeWZLdcJ8J7A4FuHMJlFxW3S5RA8CmNXB-GeUwR_9MtJ1BrJ4UHZi5kHMCTe7Y4EcOVI4jPaGAb_fdVGILI3UvRV-Mn1JQEYGtUZjJZ_D7p2fDN2YHbeduWxM7hUqKFodTD-aMFvaj2kghxCoaTk0KdAIb_RQ1ADxnOOWJMVH1Uz8pDlu8VDf8CAwEAAQ";

/** 4 元组 [op, slotA, slotB, slotC]，已与 mask 异或 */
export type VheInstruction = readonly [number, number, number, number];

/** RSA-OAEP unseal + AES-GCM open 程序 */
export const VHE_OPEN_PROGRAM: VheInstruction[] = [
  [142, 225, 191, 200],
  [31, 26, 225, 75],
  [95, 97, 9, 186],
  [226, 78, 87, 63],
  [110, 236, 45, 126],
  [144, 155, 104, 246],
  [255, 89, 124, 22],
];

/** GEN_KEY+GEN_IV+RSA_SEAL+AES_SEAL 程序 */
export const VHE_SEAL_PROGRAM: VheInstruction[] = [
  [99, 229, 191, 200],
  [113, 26, 225, 75],
  [177, 102, 9, 186],
  [22, 73, 82, 57],
  [57, 234, 46, 122],
  [152, 152, 105, 242],
  [31, 89, 125, 18],
  [45, 44, 13, 160],
  [168, 225, 191, 200],
];
